[versions]
agp = "8.13.2"
kotlin = "2.3.0"
android-minSdk = "33"
android-targetSdk = "36"
compose-multiplatform = "1.10.0-rc02"
androidx-lifecycle = "2.10.0-alpha07"
adaptive = "1.2.0"
ksp = "2.3.4"
runtime-annotation = "1.10.0"

kotlinxSerializationCore = "1.9.0"
androidx-activityCompose = "1.12.2"
androidx-navigation = "2.9.1"
composeHotReload = "1.0.0"
kotlinx-datetime = "0.7.1"
coroutines = "1.10.2"
koinBom = "4.1.1"
materialIconsCore = "1.7.3"
koinAnnotationsVersion = "2.3.1"
material3 = "1.10.0-alpha05"
okio = "3.16.4"
atomicfu="0.29.0"
keight = "0.0.04"
collection="1.5.0"
kotlinxCollectionsImmutable = "0.4.0"
stabilityAnalyzer = "0.6.6"

[libraries]
material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "materialIconsCore" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
material3-navigation-suite = { module = "org.jetbrains.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3" }



androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationCore" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinxSerializationCore" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = {group = "io.insert-koin", name = "koin-compose-viewmodel"}

koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koinAnnotationsVersion" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinAnnotationsVersion" }

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-coroutines-swing = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }

keight = { module = "io.github.alexzhirkevich:keight", version.ref = "keight" }
keight-core = { module = "io.github.alexzhirkevich:keight-core", version.ref = "keight" }
androidx-collection = { module = "androidx.collection:collection", version.ref = "collection" }

components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }
kotlinx-collections-immutable = {group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
runtime-annotation = { module = "androidx.compose.runtime:runtime-annotation", version.ref = "runtime-annotation" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload"}
stability-analyzer = {id = "com.github.skydoves.compose.stability.analyzer", version.ref = "stabilityAnalyzer" }